import AppKit
import Foundation

/// Watches the general pasteboard and records what the user copies.
///
/// macOS publishes no change notification for the pasteboard, so this polls
/// `changeCount` — an integer read, no data access — and only inspects contents
/// when that number actually moves.
///
/// A clipboard history is the most sensitive thing this app could keep, so the
/// filtering is the point of the type rather than a detail of it:
///
/// * it records nothing unless the user switched it on,
/// * it honours the `org.nspasteboard.*` marker types that password managers
///   and other apps use to say "do not record this",
/// * it never records from an app on the excluded list, which ships with the
///   common password managers already in it,
/// * and it skips NotchShot's own writes, which are pasteboard *promises* whose
///   data must not be read or the deferred encode happens anyway.
@MainActor
public final class ClipboardMonitor {
    public static let shared = ClipboardMonitor()

    /// Marker types from the nspasteboard.org convention. An app that sets any
    /// of these is asking clipboard managers not to keep the clipping.
    ///
    /// `ConcealedType` is what 1Password, Bitwarden and Keychain Access set on
    /// a copied password. Honouring it is the difference between a clipboard
    /// history and a password log.
    nonisolated static let excludedMarkerTypes: [NSPasteboard.PasteboardType] = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
        // Some apps still use the older spelling.
        NSPasteboard.PasteboardType("com.agilebits.onepassword"),
        NSPasteboard.PasteboardType("Pasteboard generator type"),
    ]

    /// Apps whose clipboard traffic is passwords by definition. The user can
    /// add to this in Settings; these are the defaults so the safe behaviour
    /// does not depend on anyone thinking of it first.
    public nonisolated static let defaultExcludedBundleIDs: Set<String> = [
        "com.agilebits.onepassword7",
        "com.1password.1password",
        "com.bitwarden.desktop",
        "com.apple.keychainaccess",
        "org.keepassxc.keepassxc",
        "com.dashlane.dashlanephonefinal",
        "in.sinew.Enpass-Desktop",
        "com.lastpass.LastPass",
        "com.robinlinus.NordPass",
        "com.proton.pass.electron",
    ]

    /// Polling cadence. Fast enough that copying then opening the notch feels
    /// immediate, slow enough to be invisible in Activity Monitor.
    nonisolated static let pollInterval: TimeInterval = 0.6

    private let pasteboard: NSPasteboard
    private let store: ClipboardStore
    private var timer: Timer?
    private var lastChangeCount: Int
    public private(set) var isRunning = false

    /// Bundle IDs that held focus at any point since the last poll.
    ///
    /// `frontmostApplication` answers "who is receiving events now", not "who
    /// wrote the pasteboard". Sampling it up to `pollInterval` after the fact
    /// means a password copied from an excluded app and followed by a fast
    /// switch would be attributed to whatever the user switched *to* — and
    /// recorded. Every activation in the window is collected instead, and the
    /// clipping is refused if any of them is excluded.
    private(set) var focusWindow: [String] = []
    private var activationObserver: (any NSObjectProtocol)?

    /// Fires when something new was recorded, so the notch can acknowledge it.
    public var onCapture: ((ClipboardEntry) -> Void)?

    public init(
        pasteboard: NSPasteboard = .general,
        store: ClipboardStore = .shared
    ) {
        self.pasteboard = pasteboard
        self.store = store
        lastChangeCount = pasteboard.changeCount
    }

    public func start() {
        guard !isRunning, Preferences.shared.clipboardEnabled else { return }
        isRunning = true
        // Seed rather than replay: whatever is on the pasteboard right now was
        // copied before the user turned this on, and recording it would be a
        // surprise.
        lastChangeCount = pasteboard.changeCount
        focusWindow = NSWorkspace.shared.frontmostApplication?.bundleIdentifier.map { [$0] } ?? []
        activationObserver = NSWorkspace.shared.notificationCenter.addObserver(
            forName: NSWorkspace.didActivateApplicationNotification,
            object: nil,
            queue: .main
        ) { [weak self] notification in
            let key = NSWorkspace.applicationUserInfoKey
            let app = notification.userInfo?[key] as? NSRunningApplication
            let bundleID = app?.bundleIdentifier
            MainActor.assumeIsolated { self?.noteActivation(bundleID) }
        }
        let timer = Timer(timeInterval: Self.pollInterval, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.poll() }
        }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    public func stop() {
        isRunning = false
        timer?.invalidate()
        timer = nil
        if let activationObserver {
            NSWorkspace.shared.notificationCenter.removeObserver(activationObserver)
        }
        activationObserver = nil
        focusWindow = []
    }

    /// Bounded so a burst of switching cannot grow this without limit; the
    /// oldest entries are the least likely to be the pasteboard's author.
    func noteActivation(_ bundleID: String?) {
        guard let bundleID else { return }
        focusWindow.append(bundleID)
        if focusWindow.count > 16 { focusWindow.removeFirst(focusWindow.count - 16) }
    }

    public func reconcile() {
        if Preferences.shared.clipboardEnabled {
            start()
        } else {
            stop()
        }
    }

    // MARK: Polling

    func poll(now: Date = Date()) {
        // Rotate the attribution window on *every* poll, before anything can
        // return early. Only a change detected on this poll can have been
        // written by an app focused since the previous one; carrying the window
        // forward until the next change instead would let a password manager
        // visited once, long ago and without copying anything, go on
        // suppressing unrelated clippings indefinitely.
        let frontmost = NSWorkspace.shared.frontmostApplication
        let candidates = focusWindow + (frontmost?.bundleIdentifier.map { [$0] } ?? [])
        focusWindow = frontmost?.bundleIdentifier.map { [$0] } ?? []

        let changeCount = pasteboard.changeCount
        guard changeCount != lastChangeCount else { return }
        lastChangeCount = changeCount
        guard Preferences.shared.clipboardEnabled else { return }

        // Our own copy is a promise. Reading it would force the encode the
        // promise exists to defer — on every capture.
        guard changeCount != ImageExport.lastSelfWriteChangeCount else { return }

        guard Self.shouldRecord(
            pasteboard: pasteboard,
            candidateBundleIDs: candidates,
            excludedBundleIDs: Preferences.shared.clipboardExcludedBundleIDs
        ) else { return }

        guard let result = readEntry(
            sourceName: frontmost?.localizedName,
            sourceBundleID: frontmost?.bundleIdentifier,
            now: now
        ) else { return }

        switch result {
        case let .immediate(entry):
            if let recorded = store.record(entry) {
                onCapture?(recorded)
            }
        case let .image(entry, data):
            // Pasteboard access stays on the main actor, as AppKit requires;
            // bounded image decoding and PNG persistence do not.
            Task { [weak self] in
                guard let self else { return }
                let image = await Task.detached(priority: .utility) {
                    SafeImageFile.cgImage(
                        from: data,
                        limits: SafeImageFile.Limits(
                            maximumBytes: ClipboardStore.maximumImageBytes,
                            maximumDimension: 32_768,
                            maximumPixels: 50_000_000
                        )
                    )
                }.value
                guard let image,
                      let recorded = await self.store.recordImage(entry, image: image) else { return }
                self.onCapture?(recorded)
            }
        }
    }

    /// Whether this clipping may be recorded at all. Pure, so the rules are
    /// testable without a real pasteboard change.
    nonisolated static func shouldRecord(
        markerTypes: Set<String>,
        sourceBundleID: String?,
        excludedBundleIDs: Set<String>
    ) -> Bool {
        shouldRecord(
            markerTypes: markerTypes,
            candidateBundleIDs: sourceBundleID.map { [$0] } ?? [],
            excludedBundleIDs: excludedBundleIDs
        )
    }

    /// Fails closed across the whole attribution window: if *any* app that
    /// could have written this clipping is excluded, nothing is recorded.
    /// Losing an occasional legitimate clipping is the correct trade against
    /// filing a password under the wrong app's name.
    nonisolated static func shouldRecord(
        markerTypes: Set<String>,
        candidateBundleIDs: [String],
        excludedBundleIDs: Set<String>
    ) -> Bool {
        for marker in excludedMarkerTypes where markerTypes.contains(marker.rawValue) {
            return false
        }
        for bundleID in candidateBundleIDs {
            if excludedBundleIDs.contains(bundleID) { return false }
            // NotchShot recording its own clipboard writes would be a loop.
            if bundleID == Bundle.main.bundleIdentifier { return false }
        }
        return true
    }

    private static func shouldRecord(
        pasteboard: NSPasteboard,
        candidateBundleIDs: [String],
        excludedBundleIDs: Set<String>
    ) -> Bool {
        let available = Set((pasteboard.types ?? []).map(\.rawValue))
        return shouldRecord(
            markerTypes: available,
            candidateBundleIDs: candidateBundleIDs,
            excludedBundleIDs: excludedBundleIDs
        )
    }

    /// Classifies the clipping. Order matters: files and images are checked
    /// before text, because both also advertise a string representation.
    private enum ReadResult {
        case immediate(ClipboardEntry)
        case image(ClipboardEntry, Data)
    }

    private func readEntry(
        sourceName: String?,
        sourceBundleID: String?,
        now: Date
    ) -> ReadResult? {
        if let urls = pasteboard.readObjects(
            forClasses: [NSURL.self],
            options: [.urlReadingFileURLsOnly: true]
        ) as? [URL], !urls.isEmpty {
            let limited = Array(urls.prefix(64).map(\.standardizedFileURL))
            let identities = limited.compactMap {
                SafeAssetFile.fileSystemIdentity(
                    at: $0,
                    maximumBytes: SafeAssetFile.maximumExternalBytes,
                    allowsDirectory: true
                )
            }
            // One unsafe/symlinked member suppresses the whole clipping. A
            // partial file list would look complete but paste something else.
            guard identities.count == limited.count else { return nil }
            let paths = limited.map(\.path)
            return .immediate(
                ClipboardEntry(
                    kind: .files,
                    filePaths: paths,
                    fileIdentities: identities,
                    sourceApplicationName: sourceName,
                    sourceApplicationBundleID: sourceBundleID,
                    createdAt: now,
                    contentHash: ClipboardEntry.hash(forText: paths.joined(separator: "\n"))
                )
            )
        }

        if let imageType = pasteboard.availableType(from: [.png, .tiff]),
           let data = pasteboard.data(forType: imageType) {
            guard data.count <= ClipboardStore.maximumImageBytes else { return nil }
            return .image(
                ClipboardEntry(
                    kind: .image,
                    sourceApplicationName: sourceName,
                    sourceApplicationBundleID: sourceBundleID,
                    createdAt: now,
                    contentHash: ClipboardEntry.hash(for: data)
                ),
                data
            )
        }

        guard let string = pasteboard.string(forType: .string) else { return nil }
        let trimmed = string.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return nil }

        var text = string
        if text.utf8.count > ClipboardStore.maximumTextBytes {
            text = String(text.prefix(ClipboardStore.maximumTextBytes / 4))
        }
        return .immediate(
            ClipboardEntry(
                kind: Self.classify(trimmed),
                text: text,
                sourceApplicationName: sourceName,
                sourceApplicationBundleID: sourceBundleID,
                createdAt: now,
                contentHash: ClipboardEntry.hash(forText: text)
            )
        )
    }

    /// Text, a link, or a colour. Kept narrow deliberately: a wrong guess here
    /// only changes an icon, and an over-eager classifier that calls every
    /// slash-containing string a link is worse than a plain text row.
    nonisolated static func classify(_ trimmed: String) -> ClipboardKind {
        if trimmed.count <= 9, trimmed.hasPrefix("#"),
           trimmed.dropFirst().allSatisfy(\.isHexDigit),
           [3, 4, 6, 8].contains(trimmed.count - 1) {
            return .color
        }
        if !trimmed.contains(where: \.isWhitespace),
           let url = URL(string: trimmed),
           let scheme = url.scheme?.lowercased(),
           ["http", "https", "ftp", "mailto"].contains(scheme),
           url.host?.isEmpty == false || scheme == "mailto" {
            return .link
        }
        return .text
    }

    // MARK: Paste-back

    /// Puts an entry back on the pasteboard.
    ///
    /// Marked as a self-write so the poll does not immediately record it again
    /// as a fresh clipping from NotchShot.
    public func copyToPasteboard(_ entry: ClipboardEntry) async throws {
        switch entry.kind {
        case .image:
            guard let url = entry.imageURL else {
                throw NotchShotError.exportFailed("That clipboard image is no longer available")
            }
            let image = await Task.detached(priority: .userInitiated) {
                SafeImageFile.cgImage(at: url, limits: .generated)
            }.value
            guard let image else {
                throw NotchShotError.exportFailed("That clipboard image is no longer available")
            }
            ImageExport.copyToPasteboard(image)
        case .files:
            let urls = try Self.validatedFileURLs(for: entry)
            pasteboard.clearContents()
            guard pasteboard.writeObjects(urls.map { $0 as NSURL }) else {
                throw NotchShotError.exportFailed("The selected files could not be copied")
            }
            lastChangeCount = pasteboard.changeCount
        case .text, .link, .color:
            guard let text = entry.text else {
                throw NotchShotError.exportFailed("That clipboard entry is empty")
            }
            ImageExport.copyToPasteboard(text: text)
        }
        lastChangeCount = pasteboard.changeCount
    }

    nonisolated static func validatedFileURLs(for entry: ClipboardEntry) throws -> [URL] {
        guard entry.kind == .files,
              !entry.filePaths.isEmpty,
              let identities = entry.fileIdentities,
              identities.count == entry.filePaths.count else {
            throw NotchShotError.exportFailed(
                "This older file clipping cannot be verified safely. Copy the files again to refresh it."
            )
        }
        let urls = entry.filePaths.map { URL(fileURLWithPath: $0).standardizedFileURL }
        for (url, identity) in zip(urls, identities) {
            try SafeAssetFile.requireCurrentItem(
                at: url,
                expectedIdentity: identity,
                maximumBytes: SafeAssetFile.maximumExternalBytes,
                allowsDirectory: true
            )
        }
        return urls
    }

    /// Copies derived text without letting the monitor record its own write as
    /// a second clipboard-history entry.
    public func copyDerivedTextToPasteboard(_ text: String) {
        guard !text.isEmpty else { return }
        ImageExport.copyToPasteboard(text: text)
        lastChangeCount = pasteboard.changeCount
    }
}
