import AppKit
import Foundation
import Testing

@testable import NotchShotKit

/// A clipboard history is the most sensitive store this app keeps, so the rules
/// about what never gets recorded are pinned first and hardest.
@Suite("Clipboard privacy")
@MainActor
struct ClipboardPrivacyTests {

    private let excluded = ClipboardMonitor.defaultExcludedBundleIDs

    @Test("A concealed clipping is never recorded")
    func concealedIsRefused() {
        // What 1Password, Bitwarden and Keychain Access set on a copied
        // password. Honouring it is what separates a clipboard history from a
        // password log.
        #expect(!ClipboardMonitor.shouldRecord(
            markerTypes: ["public.utf8-plain-text", "org.nspasteboard.ConcealedType"],
            sourceBundleID: "com.example.editor",
            excludedBundleIDs: excluded
        ))
    }

    @Test("Transient and auto-generated clippings are never recorded")
    func transientIsRefused() {
        for marker in ["org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType"] {
            #expect(!ClipboardMonitor.shouldRecord(
                markerTypes: ["public.utf8-plain-text", marker],
                sourceBundleID: "com.example.editor",
                excludedBundleIDs: excluded
            ), "\(marker) should suppress recording")
        }
    }

    @Test("Copying from an excluded app is never recorded")
    func excludedAppIsRefused() {
        #expect(!ClipboardMonitor.shouldRecord(
            markerTypes: ["public.utf8-plain-text"],
            sourceBundleID: "com.bitwarden.desktop",
            excludedBundleIDs: excluded
        ))
    }

    @Test("The common password managers are excluded by default")
    func passwordManagersExcludedOutOfTheBox() {
        // The safe behaviour must not depend on the user thinking of it first.
        for bundleID in ["com.1password.1password", "com.bitwarden.desktop", "com.apple.keychainaccess"] {
            #expect(ClipboardMonitor.defaultExcludedBundleIDs.contains(bundleID))
        }
    }

    @Test("An ordinary clipping from an ordinary app is recorded")
    func ordinaryClippingIsAllowed() {
        #expect(ClipboardMonitor.shouldRecord(
            markerTypes: ["public.utf8-plain-text"],
            sourceBundleID: "com.apple.TextEdit",
            excludedBundleIDs: excluded
        ))
    }

    @Test("A row can only ever name its own image file")
    func imageURLIsConfinedToItsOwnName() {
        let entry = ClipboardEntry(kind: .image, imageFilename: "someone-elses.png", contentHash: "a")
        #expect(entry.imageURL == nil)

        let honest = ClipboardEntry(kind: .image, contentHash: "a")
        var named = honest
        named.imageFilename = "\(honest.id.uuidString).png"
        #expect(named.imageURL != nil)

        // Traversal spellings are excluded by the exact-name rule, not by
        // parsing, so this is the case that proves it.
        var traversal = honest
        traversal.imageFilename = "../../\(honest.id.uuidString).png"
        #expect(traversal.imageURL == nil)
    }

    @Test("File clippings reject a same-path replacement")
    func fileIdentityPreventsReplayOfReplacement() throws {
        let directory = FileManager.default.temporaryDirectory
            .appendingPathComponent("notchshot-clipboard-files-\(UUID().uuidString)", isDirectory: true)
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: directory) }
        let file = directory.appendingPathComponent("invoice.pdf")
        try Data("original".utf8).write(to: file)
        let identity = try #require(SafeAssetFile.fileSystemIdentity(
            at: file,
            maximumBytes: SafeAssetFile.maximumExternalBytes,
            allowsDirectory: true
        ))
        let entry = ClipboardEntry(
            kind: .files,
            filePaths: [file.path],
            fileIdentities: [identity],
            contentHash: "file"
        )
        #expect(try ClipboardMonitor.validatedFileURLs(for: entry) == [file])

        try Data("replacement with different contents".utf8)
            .write(to: file, options: .atomic)
        #expect(throws: (any Error).self) {
            _ = try ClipboardMonitor.validatedFileURLs(for: entry)
        }
    }

    @Test("Legacy file clippings fail closed until copied again")
    func legacyFileClippingNeedsRefresh() {
        let entry = ClipboardEntry(
            kind: .files,
            filePaths: ["/tmp/legacy.txt"],
            contentHash: "legacy"
        )
        #expect(throws: (any Error).self) {
            _ = try ClipboardMonitor.validatedFileURLs(for: entry)
        }
    }
}

@Suite("Clipboard classification")
struct ClipboardClassificationTests {

    @Test("Links are recognised only with a real scheme and host")
    func classifiesLinks() {
        #expect(ClipboardMonitor.classify("https://example.com/page") == .link)
        #expect(ClipboardMonitor.classify("http://example.com") == .link)
        #expect(ClipboardMonitor.classify("mailto:someone@example.com") == .link)
        // A path is not a URL, and calling it one would put a link icon on
        // half the plain text people copy.
        #expect(ClipboardMonitor.classify("/Users/test/Documents") == .text)
        #expect(ClipboardMonitor.classify("see https://example.com for more") == .text)
        #expect(ClipboardMonitor.classify("example.com") == .text)
    }

    @Test("Hex colours are recognised at every legal length")
    func classifiesColors() {
        #expect(ClipboardMonitor.classify("#fff") == .color)
        #expect(ClipboardMonitor.classify("#FF8800") == .color)
        #expect(ClipboardMonitor.classify("#FF8800CC") == .color)
        #expect(ClipboardMonitor.classify("#12345") == .text)
        #expect(ClipboardMonitor.classify("#zzzzzz") == .text)
    }

    @Test("Everything else is plain text")
    func classifiesText() {
        #expect(ClipboardMonitor.classify("just some words") == .text)
        #expect(ClipboardMonitor.classify("1234") == .text)
    }
}

@Suite("Clipboard store")
@MainActor
struct ClipboardStoreTests {

    private func makeStore() -> ClipboardStore {
        let directory = URL(fileURLWithPath: NSTemporaryDirectory())
            .appendingPathComponent("notchshot-clip-\(UUID().uuidString)", isDirectory: true)
        try? FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        return ClipboardStore(
            storeURL: directory.appendingPathComponent("clipboard.json"),
            imageDirectory: directory
        )
    }

    private func entry(_ text: String, pinned: Bool = false, at offset: TimeInterval = 0) -> ClipboardEntry {
        ClipboardEntry(
            kind: .text,
            text: text,
            createdAt: Date(timeIntervalSince1970: 1_700_000_000 + offset),
            isPinned: pinned,
            contentHash: ClipboardEntry.hash(forText: text)
        )
    }

    private func withClipboardOn(_ body: () throws -> Void) rethrows {
        let wasEnabled = Preferences.shared.clipboardEnabled
        Preferences.shared.clipboardEnabled = true
        defer { Preferences.shared.clipboardEnabled = wasEnabled }
        try body()
    }

    @Test("Nothing is recorded while the feature is off")
    func recordsNothingWhenDisabled() {
        let wasEnabled = Preferences.shared.clipboardEnabled
        Preferences.shared.clipboardEnabled = false
        defer { Preferences.shared.clipboardEnabled = wasEnabled }

        let store = makeStore()
        #expect(store.record(entry("secret")) == nil)
        #expect(store.entries.isEmpty)
    }

    @Test("Re-copying promotes the existing row instead of duplicating it")
    func reCopyPromotes() {
        withClipboardOn {
            let store = makeStore()
            store.record(entry("alpha", at: 0))
            store.record(entry("beta", at: 1))
            store.record(entry("alpha", at: 2))

            #expect(store.entries.count == 2)
            #expect(store.entries.first?.text == "alpha")
        }
    }

    @Test("Pinned rows sort above unpinned ones")
    func pinnedSortFirst() {
        withClipboardOn {
            let store = makeStore()
            store.record(entry("old", at: 0))
            store.record(entry("new", at: 10))
            let oldID = store.entries.first { $0.text == "old" }?.id

            #expect(store.entries.first?.text == "new")
            store.setPinned(true, id: try! #require(oldID))
            #expect(store.entries.first?.text == "old")
        }
    }

    @Test("Retention expires old rows but never pinned ones")
    func retentionSpartesPinned() {
        withClipboardOn {
            let wasRetention = Preferences.shared.clipboardRetentionDays
            Preferences.shared.clipboardRetentionDays = 7
            defer { Preferences.shared.clipboardRetentionDays = wasRetention }

            let store = makeStore()
            let now = Date()
            store.record(ClipboardEntry(
                kind: .text, text: "ancient",
                createdAt: now.addingTimeInterval(-30 * 86_400),
                contentHash: "ancient"
            ))
            store.record(ClipboardEntry(
                kind: .text, text: "ancient but pinned",
                createdAt: now.addingTimeInterval(-30 * 86_400),
                isPinned: true,
                contentHash: "pinned"
            ))
            store.record(ClipboardEntry(
                kind: .text, text: "recent",
                createdAt: now,
                contentHash: "recent"
            ))

            #expect(store.applyRetention(now: now) == 1)
            let remaining = Set(store.entries.compactMap(\.text))
            #expect(remaining == ["ancient but pinned", "recent"])
        }
    }

    /// History once wrote a store past the caps its own loader accepted and
    /// lost everything on the next launch. This store must not repeat it.
    @Test("The row cap is enforced on write, not discovered on read")
    func rowCapIsEnforcedOnWrite() {
        withClipboardOn {
            let store = makeStore()
            for index in 0 ..< (ClipboardStore.maximumEntryCount + 40) {
                store.record(entry("clip \(index)", at: TimeInterval(index)))
            }
            #expect(store.entries.count == ClipboardStore.maximumEntryCount)
            // Newest survive.
            #expect(store.entries.first?.text == "clip \(ClipboardStore.maximumEntryCount + 39)")
        }
    }

    @Test("A single huge clipping cannot evict the whole history")
    func oversizedClippingIsTruncatedRatherThanEvicting() {
        withClipboardOn {
            let store = makeStore()
            for index in 0 ..< 20 {
                store.record(entry("small \(index)", at: TimeInterval(index)))
            }
            let huge = String(repeating: "x", count: ClipboardStore.storeByteBudget + 1_000)
            store.record(ClipboardEntry(
                kind: .text, text: huge,
                createdAt: Date(timeIntervalSince1970: 1_700_001_000),
                contentHash: "huge"
            ))

            #expect(ClipboardStore.estimatedStoreBytes(store.entries) <= ClipboardStore.storeByteBudget)
            // The small rows are what the user actually wanted kept.
            #expect(store.entries.count > 1)
        }
    }

    @Test("Pinned and heavily escaped text still writes a readable store")
    func escapedPinnedTextStaysWithinTheRealJSONBudget() throws {
        try withClipboardOn {
            let directory = URL(fileURLWithPath: NSTemporaryDirectory())
                .appendingPathComponent("notchshot-clip-\(UUID().uuidString)", isDirectory: true)
            try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
            let storeURL = directory.appendingPathComponent("clipboard.json")
            let store = ClipboardStore(storeURL: storeURL, imageDirectory: directory)

            // Quotes and control characters expand when JSON is encoded. The
            // old estimate counted their raw UTF-8 bytes and could therefore
            // write a file larger than the loader accepted. Pinning every row
            // also proves that pin priority cannot bypass the safety cap.
            let escaped = String(repeating: "\"\u{0001}", count: 100_000)
            for index in 0 ..< 48 {
                store.record(ClipboardEntry(
                    kind: .text,
                    text: escaped,
                    createdAt: Date(timeIntervalSince1970: 1_700_000_000 + Double(index)),
                    isPinned: true,
                    contentHash: "escaped-\(index)"
                ))
            }
            try store.save()

            let size = try storeURL.resourceValues(forKeys: [.fileSizeKey]).fileSize ?? 0
            #expect(size <= ClipboardStore.maximumStoreBytes)
            let reloaded = ClipboardStore(storeURL: storeURL, imageDirectory: directory)
            #expect(!reloaded.entries.isEmpty)
            #expect(reloaded.entries.allSatisfy { $0.isPinned })
        }
    }

    @Test("A written store is one the next launch can read back")
    func roundTripsThroughDisk() throws {
        try withClipboardOn {
            let directory = URL(fileURLWithPath: NSTemporaryDirectory())
                .appendingPathComponent("notchshot-clip-\(UUID().uuidString)", isDirectory: true)
            try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
            let storeURL = directory.appendingPathComponent("clipboard.json")

            let store = ClipboardStore(storeURL: storeURL, imageDirectory: directory)
            store.record(entry("alpha", at: 0))
            store.record(entry("beta", at: 1))
            try store.save()

            let size = try storeURL.resourceValues(forKeys: [.fileSizeKey]).fileSize ?? 0
            #expect(size <= ClipboardStore.maximumStoreBytes)

            let reloaded = ClipboardStore(storeURL: storeURL, imageDirectory: directory)
            #expect(reloaded.entries.count == 2)
            #expect(reloaded.entries.first?.text == "beta")

            let leftovers = (try? FileManager.default.contentsOfDirectory(atPath: directory.path)) ?? []
            #expect(!leftovers.contains { $0.contains("corrupt-") })
        }
    }

    @Test("Labels are bounded, searchable, and survive relaunch")
    func labelsRoundTrip() throws {
        try withClipboardOn {
            let directory = URL(fileURLWithPath: NSTemporaryDirectory())
                .appendingPathComponent("notchshot-clip-\(UUID().uuidString)", isDirectory: true)
            try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
            defer { try? FileManager.default.removeItem(at: directory) }
            let storeURL = directory.appendingPathComponent("clipboard.json")
            let store = ClipboardStore(storeURL: storeURL, imageDirectory: directory)
            let recorded = try #require(store.record(entry("Invoice #2041")))

            #expect(store.setLabel("  Follow\nup Friday  ", id: recorded.id))
            #expect(store.entry(id: recorded.id)?.label == "Follow up Friday")
            #expect(store.search("follow up").map(\.id) == [recorded.id])
            try store.save()

            let reloaded = ClipboardStore(storeURL: storeURL, imageDirectory: directory)
            #expect(reloaded.entry(id: recorded.id)?.displayTitle == "Follow up Friday")
            #expect(ClipboardStore.sanitizedLabel(String(repeating: "x", count: 100))?.count == 80)
            #expect(ClipboardStore.sanitizedLabel(" \n\t ") == nil)
        }
    }

    @Test("Image OCR becomes searchable only after explicit indexing")
    func imageOCRIsExplicitAndSearchable() throws {
        try withClipboardOn {
            let store = makeStore()
            let imageEntry = ClipboardEntry(
                kind: .image,
                contentHash: "image-with-text"
            )
            let recorded = try #require(store.record(
                imageEntry,
                image: TestImage.solid(width: 24, height: 16)
            ))

            #expect(store.search("invoice").isEmpty)
            #expect(store.setRecognizedText("Invoice 2041\nDue Friday", id: recorded.id))
            #expect(store.search("invoice").map(\.id) == [recorded.id])
            #expect(store.entry(id: recorded.id)?.preview == "Invoice 2041 Due Friday")
            #expect(store.setRecognizedText(nil, id: recorded.id))
            #expect(store.search("invoice").isEmpty)
        }
    }

    @Test("Clearing keeps pinned rows when asked to")
    func clearCanKeepPinned() {
        withClipboardOn {
            let store = makeStore()
            store.record(entry("throwaway", at: 0))
            store.record(entry("keeper", pinned: true, at: 1))

            store.clear(keepingPinned: true)
            #expect(store.entries.map(\.text) == ["keeper"])

            store.clear()
            #expect(store.entries.isEmpty)
        }
    }

    @Test("A long clipping previews on one line rather than in full")
    func previewStaysShort() {
        let long = ClipboardEntry(
            kind: .text,
            text: String(repeating: "word ", count: 500),
            contentHash: "long"
        )
        #expect(long.preview.count <= 181)

        let multiline = ClipboardEntry(kind: .text, text: "one\ntwo\nthree", contentHash: "m")
        #expect(!multiline.preview.contains("\n"))
    }
}

@Suite("Clipboard source attribution")
struct ClipboardAttributionTests {
    private let excluded = ClipboardMonitor.defaultExcludedBundleIDs

    @Test("An excluded app anywhere in the focus window suppresses the clipping")
    func excludedAppEarlierInWindowIsRefused() {
        // The regression: `frontmostApplication` is sampled up to one poll
        // interval after the pasteboard changed, so copying from a password
        // manager and switching away fast used to file the secret under
        // whatever app the user landed on.
        #expect(!ClipboardMonitor.shouldRecord(
            markerTypes: ["public.utf8-plain-text"],
            candidateBundleIDs: ["com.bitwarden.desktop", "com.apple.TextEdit"],
            excludedBundleIDs: excluded
        ))
    }

    @Test("Order within the focus window does not matter")
    func excludedAppLastInWindowIsRefused() {
        #expect(!ClipboardMonitor.shouldRecord(
            markerTypes: ["public.utf8-plain-text"],
            candidateBundleIDs: ["com.apple.TextEdit", "com.1password.1password"],
            excludedBundleIDs: excluded
        ))
    }

    @Test("A window of ordinary apps is still recorded")
    func ordinaryFocusWindowIsAllowed() {
        #expect(ClipboardMonitor.shouldRecord(
            markerTypes: ["public.utf8-plain-text"],
            candidateBundleIDs: ["com.apple.TextEdit", "com.apple.Safari"],
            excludedBundleIDs: excluded
        ))
    }

    @Test("An empty focus window falls back to marker rules alone")
    func emptyWindowUsesMarkersOnly() {
        #expect(ClipboardMonitor.shouldRecord(
            markerTypes: ["public.utf8-plain-text"],
            candidateBundleIDs: [],
            excludedBundleIDs: excluded
        ))
        #expect(!ClipboardMonitor.shouldRecord(
            markerTypes: ["org.nspasteboard.ConcealedType"],
            candidateBundleIDs: [],
            excludedBundleIDs: excluded
        ))
    }
}

@Suite("Clipboard focus-window rotation")
@MainActor
struct ClipboardFocusWindowTests {
    private func makeMonitor() -> ClipboardMonitor {
        let scratch = URL(fileURLWithPath: NSTemporaryDirectory())
            .appendingPathComponent("NotchShotFocusWindow-\(UUID().uuidString)", isDirectory: true)
        let pasteboard = NSPasteboard(name: NSPasteboard.Name("NotchShotFocusWindow-\(UUID().uuidString)"))
        pasteboard.clearContents()
        return ClipboardMonitor(
            pasteboard: pasteboard,
            store: ClipboardStore(
                storeURL: scratch.appendingPathComponent("clipboard.json"),
                imageDirectory: scratch
            )
        )
    }

    @Test("A poll with no pasteboard change still rotates the window")
    func quietPollRotatesWindow() {
        let monitor = makeMonitor()
        // An excluded app held focus at some point in the past...
        monitor.noteActivation("com.bitwarden.desktop")
        #expect(monitor.focusWindow.contains("com.bitwarden.desktop"))

        // ...and quiet polls happened since, with nothing copied. Were the
        // window rotated only when a change is detected, that stale visit
        // would go on suppressing every later clipping.
        monitor.poll()
        monitor.poll()
        #expect(!monitor.focusWindow.contains("com.bitwarden.desktop"))
    }

    @Test("The window is bounded so rapid switching cannot grow it")
    func windowIsBounded() {
        let monitor = makeMonitor()
        for index in 0 ..< 100 {
            monitor.noteActivation("com.example.app\(index)")
        }
        #expect(monitor.focusWindow.count <= 16)
        // The most recent activations are the ones worth keeping.
        #expect(monitor.focusWindow.contains("com.example.app99"))
    }
}
